/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PubMedFetcherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  articleType: "Article"
};
var PubMedFetcherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "fetch-article",
      name: "Fetch Article from PubMed/DOI",
      callback: () => {
        new ArticleInputModal(this.app, this.settings, (input) => {
          this.fetchArticle(input);
        }).open();
      }
    });
    this.addCommand({
      id: "fetch-article-from-selection",
      name: "Fetch Article from Selected PubMed/DOI",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection().trim();
        if (selection) {
          this.fetchArticleAndInsert(selection, editor);
        } else {
          new import_obsidian.Notice("Please select a PubMed ID or DOI first");
        }
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        const selection = editor.getSelection().trim();
        if (selection && (this.extractPubMedId(selection) || this.extractDOI(selection))) {
          menu.addItem((item) => {
            item.setTitle("Fetch Article Info").setIcon("download").onClick(() => {
              this.fetchArticleAndInsert(selection, editor);
            });
          });
        }
      })
    );
    this.addSettingTab(new PubMedFetcherSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isValidDOI(doi) {
    return /^10\.\d+\/.+$/.test(doi);
  }
  extractPubMedId(input) {
    const urlMatch = input.match(/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)/);
    if (urlMatch) return urlMatch[1];
    if (/^\d+$/.test(input)) return input;
    return null;
  }
  extractDOI(input) {
    const doiUrlMatch = input.match(/doi\.org\/(10\.\d+\/.+?)(?:[#?]|$)/);
    if (doiUrlMatch) return doiUrlMatch[1];
    if (this.isValidDOI(input)) return input;
    return null;
  }
  async findPubMedIdFromDOI(doi) {
    var _a;
    try {
      const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi";
      const params = new URLSearchParams({
        db: "pubmed",
        term: `"${doi}"[DOI]`,
        retmode: "json",
        retmax: "1"
      });
      if (this.settings.apiKey) {
        params.append("api_key", this.settings.apiKey);
      }
      const response = await fetch(`${baseUrl}?${params}`);
      if (!response.ok) {
        return null;
      }
      const data = await response.json();
      const idList = (_a = data.esearchresult) == null ? void 0 : _a.idlist;
      return idList && idList.length > 0 ? idList[0] : null;
    } catch (error) {
      console.error("Error searching PubMed by DOI:", error);
      return null;
    }
  }
  async fetchArticle(input) {
    const trimmedInput = input.trim();
    const pubmedId = this.extractPubMedId(trimmedInput);
    if (pubmedId) {
      await this.fetchByPubMedId(pubmedId);
      return;
    }
    const doi = this.extractDOI(trimmedInput);
    if (doi) {
      const pubmedId2 = await this.findPubMedIdFromDOI(doi);
      if (pubmedId2) {
        await this.fetchByPubMedIdWithDOI(pubmedId2, doi);
      } else {
        await this.fetchByDOI(doi);
      }
      return;
    }
    new import_obsidian.Notice("Invalid input. Please enter a valid PubMed ID, DOI, or URL.");
  }
  async fetchArticleAndInsert(input, editor) {
    const trimmedInput = input.trim();
    const pubmedId = this.extractPubMedId(trimmedInput);
    if (pubmedId) {
      await this.fetchByPubMedIdAndInsert(pubmedId, editor);
      return;
    }
    const doi = this.extractDOI(trimmedInput);
    if (doi) {
      const pubmedId2 = await this.findPubMedIdFromDOI(doi);
      if (pubmedId2) {
        await this.fetchByPubMedIdAndInsertWithDOI(pubmedId2, doi, editor);
      } else {
        await this.fetchByDOIAndInsert(doi, editor);
      }
      return;
    }
    new import_obsidian.Notice("Invalid input. Please enter a valid PubMed ID, DOI, or URL.");
  }
  async fetchByPubMedId(pubmedId) {
    var _a, _b, _c;
    try {
      new import_obsidian.Notice("Fetching article from PubMed...");
      const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi";
      const params = new URLSearchParams({
        db: "pubmed",
        id: pubmedId,
        retmode: "json",
        rettype: "abstract"
      });
      if (this.settings.apiKey) {
        params.append("api_key", this.settings.apiKey);
      }
      const response = await fetch(`${baseUrl}?${params}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const result = (_a = data.result) == null ? void 0 : _a[pubmedId];
      if (!result) {
        throw new Error("Article not found");
      }
      const doi = result.doi || ((_b = result.elocationid) == null ? void 0 : _b.doi) || "";
      const articleInfo = {
        title: result.title || "No title available",
        journal: result.source || result.fulljournalname || "No journal available",
        year: result.pubdate ? result.pubdate.split(" ")[0] : "No year available",
        pubmedId,
        doi,
        articleType: ((_c = result.pubtype) == null ? void 0 : _c[0]) || this.settings.articleType || "Article"
      };
      this.displayArticleInfo(articleInfo);
    } catch (error) {
      console.error("Error fetching PubMed article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
  async fetchByPubMedIdAndInsert(pubmedId, editor) {
    var _a, _b, _c;
    try {
      new import_obsidian.Notice("Fetching article from PubMed...");
      const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi";
      const params = new URLSearchParams({
        db: "pubmed",
        id: pubmedId,
        retmode: "json",
        rettype: "abstract"
      });
      if (this.settings.apiKey) {
        params.append("api_key", this.settings.apiKey);
      }
      const response = await fetch(`${baseUrl}?${params}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const result = (_a = data.result) == null ? void 0 : _a[pubmedId];
      if (!result) {
        throw new Error("Article not found");
      }
      const doi = result.doi || ((_b = result.elocationid) == null ? void 0 : _b.doi) || "";
      const articleInfo = {
        title: result.title || "No title available",
        journal: result.source || result.fulljournalname || "No journal available",
        year: result.pubdate ? result.pubdate.split(" ")[0] : "No year available",
        pubmedId,
        doi,
        articleType: ((_c = result.pubtype) == null ? void 0 : _c[0]) || this.settings.articleType || "Article"
      };
      this.insertArticleInfo(articleInfo, editor);
    } catch (error) {
      console.error("Error fetching PubMed article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
  async fetchByDOI(doi) {
    var _a, _b, _c, _d, _e, _f, _g;
    try {
      new import_obsidian.Notice("Fetching article from DOI...");
      const baseUrl = "https://api.crossref.org/works/" + encodeURIComponent(doi);
      const response = await fetch(baseUrl);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const message = data.message;
      if (!message) {
        throw new Error("Article not found");
      }
      const articleInfo = {
        title: ((_a = message.title) == null ? void 0 : _a[0]) || "No title available",
        journal: ((_b = message["short-container-title"]) == null ? void 0 : _b[0]) || ((_c = message["container-title"]) == null ? void 0 : _c[0]) || "No journal available",
        year: ((_g = (_f = (_e = (_d = message.created) == null ? void 0 : _d["date-parts"]) == null ? void 0 : _e[0]) == null ? void 0 : _f[0]) == null ? void 0 : _g.toString()) || "No year available",
        doi,
        articleType: message.type || this.settings.articleType || "Article"
      };
      this.displayArticleInfo(articleInfo);
    } catch (error) {
      console.error("Error fetching DOI article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
  async fetchByDOIAndInsert(doi, editor) {
    var _a, _b, _c, _d, _e, _f, _g;
    try {
      new import_obsidian.Notice("Fetching article from DOI...");
      const baseUrl = "https://api.crossref.org/works/" + encodeURIComponent(doi);
      const response = await fetch(baseUrl);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const message = data.message;
      if (!message) {
        throw new Error("Article not found");
      }
      const articleInfo = {
        title: ((_a = message.title) == null ? void 0 : _a[0]) || "No title available",
        journal: ((_b = message["short-container-title"]) == null ? void 0 : _b[0]) || ((_c = message["container-title"]) == null ? void 0 : _c[0]) || "No journal available",
        year: ((_g = (_f = (_e = (_d = message.created) == null ? void 0 : _d["date-parts"]) == null ? void 0 : _e[0]) == null ? void 0 : _f[0]) == null ? void 0 : _g.toString()) || "No year available",
        doi,
        articleType: message.type || this.settings.articleType || "Article"
      };
      this.insertArticleInfo(articleInfo, editor);
    } catch (error) {
      console.error("Error fetching DOI article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
  async displayArticleInfo(info) {
    const link = info.pubmedId ? `https://pubmed.ncbi.nlm.nih.gov/${info.pubmedId}/` : `https://doi.org/${info.doi}`;
    const content = `# ${info.title}

**Journal:** ${info.journal}  
**Year:** ${info.year}  
**Link:** ${link}  
**ID:** ${info.pubmedId || info.doi}

---

*Fetched by PubMed Article Fetcher plugin*`;
    let sanitizedTitle = info.title.replace(/[^\w\s-]/g, "").trim().substring(0, 50);
    if (!sanitizedTitle) {
      sanitizedTitle = `article-${Date.now()}`;
    }
    let fileName = `${sanitizedTitle}.md`;
    let counter = 1;
    while (await this.app.vault.adapter.exists(fileName)) {
      const baseName = fileName.replace(/\.md$/, "");
      fileName = `${baseName}-${counter}.md`;
      counter++;
    }
    const file = await this.app.vault.create(fileName, content);
    new import_obsidian.Notice(`Article information saved to ${fileName}`);
  }
  insertArticleInfo(info, editor) {
    const type = info.articleType || "Article";
    if (info.pubmedId && info.doi) {
      const pubmedLink = `https://pubmed.ncbi.nlm.nih.gov/${info.pubmedId}/`;
      const doiLink = `https://doi.org/${info.doi}`;
      const citation = `![PubMed](icons/pubmed.svg) ${type}: [${info.title}](${pubmedLink}) - ${info.year}, ${info.journal} [![DOI](icons/doi.svg)](${doiLink})`;
      editor.replaceSelection(citation);
    } else if (info.pubmedId) {
      const pubmedLink = `https://pubmed.ncbi.nlm.nih.gov/${info.pubmedId}/`;
      const citation = `![PubMed](icons/pubmed.svg) ${type}: [${info.title}](${pubmedLink}) - ${info.year}, ${info.journal}`;
      editor.replaceSelection(citation);
    } else if (info.doi) {
      const doiLink = `https://doi.org/${info.doi}`;
      const citation = `![DOI](icons/doi.svg) ${type}: [${info.title}](${doiLink}) - ${info.year}, ${info.journal}`;
      editor.replaceSelection(citation);
    }
    new import_obsidian.Notice("Article information inserted");
  }
  async fetchByPubMedIdWithDOI(pubmedId, doi) {
    var _a, _b;
    try {
      new import_obsidian.Notice("Fetching article from PubMed...");
      const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi";
      const params = new URLSearchParams({
        db: "pubmed",
        id: pubmedId,
        retmode: "json",
        rettype: "abstract"
      });
      if (this.settings.apiKey) {
        params.append("api_key", this.settings.apiKey);
      }
      const response = await fetch(`${baseUrl}?${params}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const result = (_a = data.result) == null ? void 0 : _a[pubmedId];
      if (!result) {
        throw new Error("Article not found");
      }
      const articleInfo = {
        title: result.title || "No title available",
        journal: result.source || result.fulljournalname || "No journal available",
        year: result.pubdate ? result.pubdate.split(" ")[0] : "No year available",
        pubmedId,
        doi,
        articleType: ((_b = result.pubtype) == null ? void 0 : _b[0]) || this.settings.articleType || "Article"
      };
      this.displayArticleInfo(articleInfo);
    } catch (error) {
      console.error("Error fetching PubMed article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
  async fetchByPubMedIdAndInsertWithDOI(pubmedId, doi, editor) {
    var _a, _b;
    try {
      new import_obsidian.Notice("Fetching article from PubMed...");
      const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi";
      const params = new URLSearchParams({
        db: "pubmed",
        id: pubmedId,
        retmode: "json",
        rettype: "abstract"
      });
      if (this.settings.apiKey) {
        params.append("api_key", this.settings.apiKey);
      }
      const response = await fetch(`${baseUrl}?${params}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      const result = (_a = data.result) == null ? void 0 : _a[pubmedId];
      if (!result) {
        throw new Error("Article not found");
      }
      const articleInfo = {
        title: result.title || "No title available",
        journal: result.source || result.fulljournalname || "No journal available",
        year: result.pubdate ? result.pubdate.split(" ")[0] : "No year available",
        pubmedId,
        doi,
        articleType: ((_b = result.pubtype) == null ? void 0 : _b[0]) || this.settings.articleType || "Article"
      };
      this.insertArticleInfo(articleInfo, editor);
    } catch (error) {
      console.error("Error fetching PubMed article:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
      new import_obsidian.Notice(`Error fetching article: ${errorMessage}`);
    }
  }
};
var ArticleInputModal = class extends import_obsidian.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter PubMed ID or DOI" });
    const input = contentEl.createEl("input", {
      type: "text",
      placeholder: "PubMed ID (e.g., 38570095) or DOI (e.g., 10.1016/j.clinme.2024.100038)"
    });
    input.style.width = "100%";
    input.style.marginBottom = "20px";
    const submitBtn = contentEl.createEl("button", { text: "Fetch Article" });
    submitBtn.onclick = () => {
      this.onSubmit(input.value);
      this.close();
    };
    input.addEventListener("keypress", (e) => {
      if (e.key === "Enter") {
        this.onSubmit(input.value);
        this.close();
      }
    });
    input.focus();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var PubMedFetcherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "PubMed Article Fetcher Settings" });
    new import_obsidian.Setting(containerEl).setName("NCBI API Key (Optional)").setDesc("Enter your NCBI API key for higher rate limits. Get one from https://www.ncbi.nlm.nih.gov/account/dev/").addText((text) => text.setPlaceholder("Your NCBI API key").setValue(this.plugin.settings.apiKey || "").onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
  }
};
